version: '3.3'

services:
  api:
    build:
      context: .
      cache_from:
        - debian:stretch
        - multichannel_api:latest
    ports:
      - 5000:5000
    volumes:
      - ./:/root/api/
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    # update to newer version time to time
    # might bork something when upgrated
    # needs testing when updated
    image: "mongo:4.1"
    ports:
      - 27018:27017
    networks:
      - backend
    command: mongod --ipv6 --noauth

  irc:
    build:
      context: ./MultiChannel-IRC-bot/
      cache_from:
        - debian:stretch
        - multichannel_irc:latest
    ports:
      - 8000:8000
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:
    external: false
    driver: "bridge"
