version: '3.3'

services:
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/root/api/
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: "mongo:latest"
    ports:
      - 27018:27017
    networks:
      - backend
    command: mongod --ipv6 --noauth

  irc:
    build:
      context: ./MultiChannel-IRC-bot/
    ports:
      - 8000:8000
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
