version: '3.3'

services:
  api:
    build:
      context: .
      cache_from:
        - debian:stretch
        - multichannel_api:latest
    ports:
      - 5000:5000
    volumes:
      - ./:/root/api/
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    # update to newer version time to time
    # might bork something when upgrated
    # needs testing when updated
    image: "mongo:4.1"
    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - LC_CTYPE="en_US.UTF-8"
      - LC_ALL=en_US.UTF-8
    ports:
      - 27018:27017
    networks:
      - backend
    command: mongod --ipv6 --noauth  # TODO add database authentication scripts

networks:
  backend:
    external: false
    driver: "bridge"
