version: '3'

services:
  api:
    build: .
    ports:
      - 5000:5000
    links:
      - "mongo"
    depends_on:
      - "mongo"

  mongo:
    image: "mongo:latest"
    volumes:
      - ./data/db
    ports:
      - 27017:27017

volumes:
  db-data:
