version: '3.3'

services:
  api:
    build: .
    ports:
      - 5000:5000
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: "mongo:latest"
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27018:27017
    networks:
      - backend
    command: mongod --ipv6 --noauth

networks:
  backend:
    driver: "bridge"
